// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';


function h(a, b) {
  return a + b | 0;
}

console.log("Hello from Reason!");

exports.h = h;
/*  Not a pure module */
